plugins {
    id "com.android.application"
    id "com.chaquo.python"
}

layout.buildDirectory = rootProject.layout.buildDirectory.dir("app")

android {
    namespace "com.local.comicreader"
    compileSdk 35

    signingConfigs {
        debug {
            storeFile rootProject.file("signing/debug-signing.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }

    defaultConfig {
        applicationId "com.local.comicreader"
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName "1.0.1"

        ndk {
            abiFilters "arm64-v8a", "x86_64"
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
        resources {
            excludes += [
                "META-INF/DEPENDENCIES",
                "META-INF/LICENSE",
                "META-INF/LICENSE.txt",
                "META-INF/NOTICE",
                "META-INF/NOTICE.txt"
            ]
        }
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sourceSets {
        main {
            manifest.srcFile "AndroidManifest.xml"
            java.srcDirs = ["java"]
            res.srcDirs = ["res"]
        }
    }
}

dependencies {
    implementation "androidx.core:core:1.13.1"
}

chaquopy {
    defaultConfig {
        buildPython System.getenv("CHAQUOPY_BUILD_PYTHON") ?: "python"
        version = "3.12"
        pip {
            options "--no-cache-dir"
            install "commonx==0.6.38"
            install "requests==2.32.3"
            install "PyYAML"
            install "pillow"
            install "pycryptodome"
            install "chaquopy-libjpeg==1.5.3"
            install "chaquopy-freetype==2.9.1"
            options "--no-deps"
            install "jmcomic==2.7.7"
        }
    }

    sourceSets {
        main {
            srcDir "python"
        }
    }
}
